### ISSUE TITLE
Fail to start gdc-client when running `.\gdc-client.exe -h`  in cmd on windows 8.1

### ISSUE THREAD

**Issue by AChaoZJU** [NCI-GDC/gdc-client#131]
I have been trying to start `gdc-client` since yesterday.  It works on windows 10.

My friend fail to start it on windows 8.  Information of error and environment is given.

- environment

```
windows 8.1

cmd
```

- error:

![_20171225155028](https://user-images.githubusercontent.com/17509647/34335737-31490cba-e98c-11e7-898f-69301e9bcc9e.jpg)

I have searched google for help but found nothing that can help me.

**Comment by zflamig** [comment]
If you haven't already, it may be worth contacting the GDC HelpDesk for your error -> support@nci-gdc.datacommons.io
