### ISSUE TITLE
Import from parcel fails

### ISSUE THREAD

**Issue by soerenmueller** [NCI-GDC/gdc-client#80]
Hi,
after installing the gdc client to a local directory I get the following error:

/gdc_client/log/log.py", line 4, in <module>
    from parcel import colored
ImportError: cannot import name colored

The parcel python package is successfully installed, I am using python 2.7, and I can also import the parcel package. 

Does anyone have a hint what I'm missing here? 

Thanks,
Soren

**Comment by soerenmueller** [comment]
Hi,

solved the issue. I had another parcel python package installed. After removal everything works fine.

Soren

**Comment by dankolbman** [comment]
Glad things worked out! Thanks for following up on it!
