### ISSUE TITLE
Publish releases on PyPi

### ISSUE THREAD

**Issue by serverhorror** [NCI-GDC/gdc-client#83]
It would be helpful to publish releases on PyPi.

**Comment by purplepeopleeater** [comment]
Github issues are not routinely monitored by the GDC team.  For questions to the GDC please contact the GDC Help Desk (support@nci-gdc.datacommons.io).    
--GDC Support Team

**Comment by serverhorror** [comment]
So remove the issues altogether from this repo. It is directly available under Settings. (If I may be so bold and do that right now: Please close this issue if you're not dealing with it here...)
